name: lifted_gan
channels:
- pytorch3d
- pytorch
- conda-forge
- anaconda
- defaults
dependencies:
- _libgcc_mutex=0.1=main
- backcall=0.2.0=py_0
- ipython=7.15.0=py36_0
- libedit=3.1=heed3624_0
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=9.1.0=hdf63c60_0
- libsodium=1.0.18=h7b6447c_0
- libstdcxx-ng=9.1.0=hdf63c60_0
- ncurses=6.0=h06874d7_1
- prompt-toolkit=3.0.5=py_0
- python=3.6.3=hcad60d5_0
- pyzmq=19.0.2=py36he6710b0_1
- readline=7.0=hac23ff0_3
- sqlite=3.23.1=he433501_0
- tk=8.6.10=hbc83047_0
- fvcore=0.1.1.post20200716=py_0
- portalocker=1.7.0=py36h9f0ad1d_0
- python_abi=3.6=1_cp36m
- pyyaml=5.3.1=py36h8c4c3a4_0
- tabulate=0.8.7=pyh9f0ad1d_0
- termcolor=1.1.0=py_2
- yacs=0.1.6=py_0
- yaml=0.2.5=h516909a_0
- argon2-cffi=20.1.0=py36h7b6447c_1
- attrs=20.3.0=pyhd3eb1b0_0
- blas=1.0=mkl
- bleach=1.5.0=py36_0
- bzip2=1.0.8=h7b6447c_0
- cairo=1.14.12=h8948797_3
- certifi=2016.2.28=py36_0
- cffi=1.14.0=py36h2e261b9_0
- cloudpickle=1.5.0=py_0
- cudatoolkit=9.2=0
- cycler=0.10.0=py36_0
- cython=0.26=py36_0
- cytoolz=0.10.1=py36h7b6447c_0
- dask-core=2.20.0=py_0
- dbus=1.13.16=hb2f20db_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_0
- expat=2.2.9=he6710b0_2
- ffmpeg=4.0=hcdf2ecd_0
- fontconfig=2.13.0=h9420a91_0
- freeglut=3.0.0=hf484d3e_5
- freetype=2.10.2=h5ab3b9f_0
- glib=2.63.1=h5a9c865_0
- graphite2=1.3.14=h23475e2_0
- gst-plugins-base=1.14.0=hbbd80ab_1
- gstreamer=1.14.0=hb453b48_1
- h5py=2.8.0=py36h61e79e4_3
- harfbuzz=1.8.8=hffaf4a1_0
- hdf5=1.8.20=hba1933b_1
- html5lib=0.9999999=py36_0
- icu=58.2=he6710b0_3
- imageio=2.9.0=py_0
- importlib-metadata=2.0.0=py_1
- importlib_metadata=2.0.0=1
- intel-openmp=2020.1=217
- ipykernel=5.3.4=py36h5ca1d4c_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.6.3=pyhd3eb1b0_1
- jasper=2.0.14=h07fcdf6_1
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.11.2=pyhd3eb1b0_0
- joblib=0.16.0=py_0
- jpeg=9b=h024ee3a_2
- json5=0.9.5=py_0
- jsonschema=3.2.0=py_2
- jupyter=1.0.0=py36_7
- jupyter_client=6.1.7=py_0
- jupyter_console=5.2.0=py36_1
- jupyter_core=4.7.0=py36h06a4308_0
- jupyterlab=2.2.6=py_0
- jupyterlab_server=1.2.0=py_0
- jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
- kiwisolver=1.2.0=py36hfd86e86_0
- libffi=3.2.1=1
- libgfortran=3.0.0=1
- libgfortran-ng=7.3.0=hdf63c60_0
- libglu=9.0.0=hf484d3e_1
- libiconv=1.14=0
- libopus=1.3.1=h7b6447c_0
- libpng=1.6.37=hbc83047_0
- libprotobuf=3.9.2=hd408876_0
- libtiff=4.0.9=he85c1e1_1
- libuuid=1.0.3=h1bed415_2
- libvpx=1.7.0=h439df22_0
- libxcb=1.14=h7b6447c_0
- libxml2=2.9.10=he19cac6_1
- lmdb=0.9.23=he6710b0_0
- markupsafe=1.0=py36_0
- matplotlib=3.1.1=py36h5429711_0
- mistune=0.7.4=py36_0
- mkl=2020.1=217
- mkl-service=2.3.0=py36he904b0f_0
- mkl_fft=1.1.0=py36h23d657b_0
- mkl_random=1.1.1=py36h0573a6f_0
- nbconvert=5.3.1=py36_0
- nbformat=5.1.2=pyhd3eb1b0_1
- networkx=1.11=py36_0
- ninja=1.9.0=py36hfd86e86_0
- nodejs=10.13.0=he6710b0_0
- notebook=6.1.4=py36_0
- numpy=1.18.5=py36ha1c710e_0
- numpy-base=1.18.5=py36hde5b4d6_0
- olefile=0.46=py_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- pandas=0.20.3=py36_0
- pandoc=2.11=hb0f4dca_0
- pandocfilters=1.4.2=py36_0
- path.py=10.3.1=py36_0
- pcre=8.44=he6710b0_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=5.4.1=py36h34e0f95_0
- pip=9.0.1=py36_1
- pixman=0.40.0=h7b6447c_0
- prometheus_client=0.9.0=pyhd3eb1b0_0
- prompt_toolkit=1.0.15=py36_0
- protobuf=3.9.2=py36he6710b0_0
- ptyprocess=0.5.2=py36_0
- pycparser=2.20=py_2
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.9.2=py36h05f1152_2
- pyrsistent=0.17.3=py36h7b6447c_0
- python-dateutil=2.6.1=py36_0
- python-lmdb=0.98=py36he6710b0_0
- pytz=2017.2=py36_0
- pywavelets=1.1.1=py36h7b6447c_0
- qt=5.9.6=h52aff34_0
- qtconsole=4.7.7=py_0
- qtpy=1.9.0=py_0
- requests=2.14.2=py36_0
- scikit-image=0.15.0=py36he6710b0_0
- scikit-learn=0.23.1=py36h423224d_0
- scipy=1.5.0=py36h0b6359f_0
- send2trash=1.5.0=pyhd3eb1b0_1
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.19.8=py36hf484d3e_0
- six=1.15.0=pyhd3eb1b0_0
- terminado=0.9.2=py36h06a4308_0
- testpath=0.3.1=py36_0
- threadpoolctl=2.1.0=pyh5ca1d4c_0
- toolz=0.10.0=py_0
- tornado=5.1=py36h14c3975_0
- tqdm=4.15.0=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.5.1=py36_0
- xz=5.2.5=h7b6447c_0
- zeromq=4.3.3=he6710b0_3
- zipp=3.4.0=pyhd3eb1b0_0
- zlib=1.2.11=0
- pytorch=1.5.1=py3.6_cuda9.2.148_cudnn7.6.3_0
- torchvision=0.6.1=py36_cu92
- pytorch3d=0.2.5=py36_cu92_pyt151
prefix: /research/prip-shiyichu/app/anaconda2/envs/pytorch

